### ISSUE TITLE
Unordered list is converted in ordered list

### ISSUE THREAD

**Issue by lacsyst** [onizet/html2openxml#63]
All is in the title

When my html contains an unordered list, this list is converted to ordered list.

`
using (WordprocessingDocument package = WordprocessingDocument.Create(generatedDocument, WordprocessingDocumentType.Document))
                {
                    MainDocumentPart mainPart = package.MainDocumentPart;
                    if (mainPart == null)
                    {
                        mainPart = package.AddMainDocumentPart();
                        new Document(new Body()).Save(mainPart);
                    }

                    HtmlConverter converter = new HtmlConverter(mainPart);
                    converter.ParseHtml(html);

                    mainPart.Document.Save();
                    docMainPart = mainPart;
                }
`

**Comment by lacsyst** [comment]
In HtmlConverter.cs file the `<ul>` tag as the same Action element than `<ol>` tag (ProcessNumberingList)

`{ "<ol>", ProcessNumberingList },
{ "<p>", ProcessParagraph },
				{ "<pre>", ProcessPre },
                { "<q>", ProcessQuote },
				{ "<span>", ProcessSpan },
                { "<section>", ProcessDiv },
                { "<s>", ProcessHtmlElement<Strike> },
				{ "<strike>", ProcessHtmlElement<Strike> },
				{ "<strong>", ProcessHtmlElement<Bold> },
				{ "<sub>", ProcessSubscript },
				{ "<sup>", ProcessSuperscript },
				{ "<table>", ProcessTable },
				{ "<tbody>", ProcessTablePart },
				{ "<td>", ProcessTableColumn },
				{ "<tfoot>", ProcessTablePart },
				{ "<th>", ProcessTableColumn },
				{ "<thead>", ProcessTablePart },
				{ "<tr>", ProcessTableRow },
				{ "<u>", ProcessUnderline },
				{ "<ul>", ProcessNumberingList },`

**Comment by ericadcg** [comment]
Hi.
I'm having this same issue and have yet to find a solution. 

Do you mind sharing your solution if you have one?

Thanks, Érica.

**Comment by ricardodemauro** [comment]
I think this was solved already. I`m using the latest version and I can see differences between those two.

**Comment by Archie-Miller** [comment]
I know I'm still having this issue.  If there is a known way to ensure this works, I'd sure like to know, otherwise I'm going to keep trying to get a ListBullet to work.
